### ISSUE TITLE
list of house-codes sent with the POST to /api/house-codes is not a JSON array

### ISSUE THREAD

**Issue by markeq** [opentrv/ors#5]
... but a comma-separated list in the testbed, despite being documented as JSON array

**Comment by dvoong** [comment]
Fixed. Works both ways now.

Modify post /api/house-codes api call to accept a json array of house codes if the content type of the request is 'application/json'. If it is not it will look for the house codes in the POST data of the request which should be in the form of a comma separted  string of house code
